version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        domain-layer:
          files:
            - "${base-path}/internal/domain/*.go"
            - "!${base-path}/internal/domain/*_test.go"
          listMode: strict
          allow:
            - $gostd
            - p2p_wallet/internal/domain
            - p2p_wallet/internal/errs
            - github.com/google/uuid
        application-service-layer:
          files:
            - "${base-path}/internal/service/*.go"
            - "!${base-path}/internal/service/*_test.go"
          listMode: strict
          allow:
            - $gostd
            - p2p_wallet/internal/domain
            - p2p_wallet/internal/dto
            - p2p_wallet/internal/errs
            - p2p_wallet/internal/service
            - p2p_wallet/internal/shared
        repository-layer:
          files:
            - "${base-path}/internal/repository/*.go"
            - "!${base-path}/internal/repository/*_test.go"
          deny:
            - pkg: p2p_wallet/internal/service
              desc: repository layer must not depend on application service layer
        handler-layer:
          files:
            - "${base-path}/internal/handler/*.go"
            - "!${base-path}/internal/handler/*_test.go"
          deny:
            - pkg: p2p_wallet/internal/repository
              desc: handler layer must not depend on repository layer
        transport-layer:
          files:
            - "${base-path}/internal/infra/server/httpserver/*.go"
            - "!${base-path}/internal/infra/server/httpserver/*_test.go"
          deny:
            - pkg: p2p_wallet/internal/repository
              desc: transport layer must not depend on repository layer
    revive:
      rules:
        - name: var-naming
        - name: package-comments
        - name: exported
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
