version: '3'

tasks:
  install-lint:
    desc: Install golangci-lint to ./bin if missing
    cmds:
      - mkdir -p bin
      - |
        if [ ! -x ./bin/golangci-lint ]; then
          GOBIN="$(pwd)/bin" go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi

  lint:
    desc: Run linter
    deps:
      - install-lint
    cmds:
      - ./bin/golangci-lint run
