@host = http://localhost:8080
@contentType = application/json
@userId = 20
@sessionId = 019c94c3-3651-7943-8e3c-ccf7bd3ef694

### Регистрация пользователя
POST {{host}}/users/register
Content-Type: {{contentType}}

{
  "login": "alex.smith",
  "password": "qwerty123",
  "name": "Alex",
  "last_name": "Smith"
}

### Логин пользователя (в ответе придет Set-Cookie: session_id=...)
POST {{host}}/users/login
Content-Type: {{contentType}}

{
  "login": "alex.smith",
  "password": "qwerty123"
}

### Логаут пользователя (нужна cookie session_id)
POST {{host}}/users/{{userId}}/logout
Cookie: session_id={{sessionId}}

### Пример ошибки логина: неверный пароль
POST {{host}}/users/login
Content-Type: {{contentType}}

{
  "login": "alex.smith",
  "password": "wrong-password"
}
