// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	SessionCookieAuthScopes = "SessionCookieAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	LastName string `json:"last_name"`

	// Login Логин (латиница)
	Login string `json:"login"`
	Name  string `json:"name"`

	// Password Пароль пользователя
	Password string `json:"password"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time  `json:"created_at"`
	Id        int64      `json:"id"`
	LastName  string     `json:"last_name"`
	Login     string     `json:"login"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserId defines model for UserId.
type UserId = int64

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest
