// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	SessionCookieAuthScopes = "SessionCookieAuth.Scopes"
)

// Defines values for CreateWalletRequestCurrency.
const (
	CreateWalletRequestCurrencyEUR CreateWalletRequestCurrency = "EUR"
	CreateWalletRequestCurrencyUSD CreateWalletRequestCurrency = "USD"
)

// Defines values for LedgerEntryCurrency.
const (
	LedgerEntryCurrencyEUR LedgerEntryCurrency = "EUR"
	LedgerEntryCurrencyUSD LedgerEntryCurrency = "USD"
)

// Defines values for WalletItemCurrency.
const (
	WalletItemCurrencyEUR WalletItemCurrency = "EUR"
	WalletItemCurrencyUSD WalletItemCurrency = "USD"
)

// Defines values for WalletItemStatus.
const (
	WalletItemStatusActive  WalletItemStatus = "active"
	WalletItemStatusBlocked WalletItemStatus = "blocked"
)

// Defines values for WalletResponseCurrency.
const (
	WalletResponseCurrencyEUR WalletResponseCurrency = "EUR"
	WalletResponseCurrencyUSD WalletResponseCurrency = "USD"
)

// Defines values for WalletResponseStatus.
const (
	WalletResponseStatusActive  WalletResponseStatus = "active"
	WalletResponseStatusBlocked WalletResponseStatus = "blocked"
)

// BalanceTransferRequest defines model for BalanceTransferRequest.
type BalanceTransferRequest struct {
	// Amount Сумма перевода в минорах
	Amount       int64 `json:"amount"`
	FromWalletId int64 `json:"from_wallet_id"`
	ToWalletId   int64 `json:"to_wallet_id"`
}

// BalanceTransferResponse defines model for BalanceTransferResponse.
type BalanceTransferResponse struct {
	Transaction LedgerTransaction `json:"transaction"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	Currency CreateWalletRequestCurrency `json:"currency"`
}

// CreateWalletRequestCurrency defines model for CreateWalletRequest.Currency.
type CreateWalletRequestCurrency string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// LedgerEntry defines model for LedgerEntry.
type LedgerEntry struct {
	// Amount Изменение баланса кошелька в минорах, отрицательное для списания и положительное для зачисления
	Amount   int64               `json:"amount"`
	Currency LedgerEntryCurrency `json:"currency"`
	Id       int64               `json:"id"`
	WalletId int64               `json:"wallet_id"`
}

// LedgerEntryCurrency defines model for LedgerEntry.Currency.
type LedgerEntryCurrency string

// LedgerTransaction defines model for LedgerTransaction.
type LedgerTransaction struct {
	CreatedAt time.Time     `json:"created_at"`
	Entries   []LedgerEntry `json:"entries"`
	Id        int64         `json:"id"`
}

// ListWalletsResponse defines model for ListWalletsResponse.
type ListWalletsResponse struct {
	Wallets []WalletItem `json:"wallets"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Id       int64  `json:"id"`
	LastName string `json:"last_name"`
	Login    string `json:"login"`
	Name     string `json:"name"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	LastName string `json:"last_name"`

	// Login Логин (латиница)
	Login string `json:"login"`
	Name  string `json:"name"`

	// Password Пароль пользователя
	Password string `json:"password"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time  `json:"created_at"`
	Id        int64      `json:"id"`
	LastName  string     `json:"last_name"`
	Login     string     `json:"login"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// WalletItem defines model for WalletItem.
type WalletItem struct {
	CreatedAt time.Time          `json:"created_at"`
	Currency  WalletItemCurrency `json:"currency"`

	// HeldAmount Удержанный баланс в минорах
	HeldAmount int64            `json:"held_amount"`
	Id         int64            `json:"id"`
	Status     WalletItemStatus `json:"status"`

	// TotalAmount Общий баланс в минорах
	TotalAmount int64     `json:"total_amount"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// WalletItemCurrency defines model for WalletItem.Currency.
type WalletItemCurrency string

// WalletItemStatus defines model for WalletItem.Status.
type WalletItemStatus string

// WalletResponse defines model for WalletResponse.
type WalletResponse struct {
	CreatedAt time.Time              `json:"created_at"`
	Currency  WalletResponseCurrency `json:"currency"`
	Id        int64                  `json:"id"`
	Status    WalletResponseStatus   `json:"status"`
	UserId    int64                  `json:"user_id"`
}

// WalletResponseCurrency defines model for WalletResponse.Currency.
type WalletResponseCurrency string

// WalletResponseStatus defines model for WalletResponse.Status.
type WalletResponseStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// UserId defines model for UserId.
type UserId = int64

// TransferBalanceParams defines parameters for TransferBalance.
type TransferBalanceParams struct {
	// XIdempotencyKey Ключ идемпотентности операции перевода
	XIdempotencyKey IdempotencyKey `json:"X-Idempotency-Key"`
}

// TransferBalanceJSONRequestBody defines body for TransferBalance for application/json ContentType.
type TransferBalanceJSONRequestBody = BalanceTransferRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest
