// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSessionRepo is an autogenerated mock type for the SessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: id
func (_m *MockSessionRepo) Delete(id int64) {
	_m.Called(id)
}

// MockSessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockSessionRepo_Expecter) Delete(id interface{}) *MockSessionRepo_Delete_Call {
	return &MockSessionRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockSessionRepo_Delete_Call) Run(run func(id int64)) *MockSessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockSessionRepo_Delete_Call) Return() *MockSessionRepo_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepo_Delete_Call) RunAndReturn(run func(int64)) *MockSessionRepo_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockSessionRepo) Get(id int64) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id int64
func (_e *MockSessionRepo_Expecter) Get(id interface{}) *MockSessionRepo_Get_Call {
	return &MockSessionRepo_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockSessionRepo_Get_Call) Run(run func(id int64)) *MockSessionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockSessionRepo_Get_Call) Return(_a0 string, _a1 error) *MockSessionRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_Get_Call) RunAndReturn(run func(int64) (string, error)) *MockSessionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: id, v, ttl
func (_m *MockSessionRepo) Set(id int64, v string, ttl time.Duration) {
	_m.Called(id, v, ttl)
}

// MockSessionRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSessionRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - id int64
//   - v string
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) Set(id interface{}, v interface{}, ttl interface{}) *MockSessionRepo_Set_Call {
	return &MockSessionRepo_Set_Call{Call: _e.mock.On("Set", id, v, ttl)}
}

func (_c *MockSessionRepo_Set_Call) Run(run func(id int64, v string, ttl time.Duration)) *MockSessionRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionRepo_Set_Call) Return() *MockSessionRepo_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepo_Set_Call) RunAndReturn(run func(int64, string, time.Duration)) *MockSessionRepo_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
