// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "p2p_wallet/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSessionRepo is an autogenerated mock type for the SessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *MockSessionRepo) Delete(key domain.SessionID) {
	_m.Called(key)
}

// MockSessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key domain.SessionID
func (_e *MockSessionRepo_Expecter) Delete(key interface{}) *MockSessionRepo_Delete_Call {
	return &MockSessionRepo_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockSessionRepo_Delete_Call) Run(run func(key domain.SessionID)) *MockSessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.SessionID))
	})
	return _c
}

func (_c *MockSessionRepo_Delete_Call) Return() *MockSessionRepo_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepo_Delete_Call) RunAndReturn(run func(domain.SessionID)) *MockSessionRepo_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockSessionRepo) Get(key domain.SessionID) (*domain.Session, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.SessionID) (*domain.Session, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(domain.SessionID) *domain.Session); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.SessionID) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key domain.SessionID
func (_e *MockSessionRepo_Expecter) Get(key interface{}) *MockSessionRepo_Get_Call {
	return &MockSessionRepo_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockSessionRepo_Get_Call) Run(run func(key domain.SessionID)) *MockSessionRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.SessionID))
	})
	return _c
}

func (_c *MockSessionRepo_Get_Call) Return(_a0 *domain.Session, _a1 error) *MockSessionRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepo_Get_Call) RunAndReturn(run func(domain.SessionID) (*domain.Session, error)) *MockSessionRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, v, ttl
func (_m *MockSessionRepo) Set(key domain.SessionID, v *domain.Session, ttl time.Duration) {
	_m.Called(key, v, ttl)
}

// MockSessionRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSessionRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key domain.SessionID
//   - v *domain.Session
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) Set(key interface{}, v interface{}, ttl interface{}) *MockSessionRepo_Set_Call {
	return &MockSessionRepo_Set_Call{Call: _e.mock.On("Set", key, v, ttl)}
}

func (_c *MockSessionRepo_Set_Call) Run(run func(key domain.SessionID, v *domain.Session, ttl time.Duration)) *MockSessionRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.SessionID), args[1].(*domain.Session), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionRepo_Set_Call) Return() *MockSessionRepo_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepo_Set_Call) RunAndReturn(run func(domain.SessionID, *domain.Session, time.Duration)) *MockSessionRepo_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
