// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "p2p_wallet/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepo is an autogenerated mock type for the WalletRepo type
type MockWalletRepo struct {
	mock.Mock
}

type MockWalletRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepo) EXPECT() *MockWalletRepo_Expecter {
	return &MockWalletRepo_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockWalletRepo) FindByUserID(ctx context.Context, userID domain.UserID) ([]*domain.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]*domain.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID) []*domain.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockWalletRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockWalletRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockWalletRepo_FindByUserID_Call {
	return &MockWalletRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockWalletRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockWalletRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID))
	})
	return _c
}

func (_c *MockWalletRepo_FindByUserID_Call) Return(_a0 []*domain.Wallet, _a1 error) *MockWalletRepo_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_FindByUserID_Call) RunAndReturn(run func(context.Context, domain.UserID) ([]*domain.Wallet, error)) *MockWalletRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, wallet
func (_m *MockWalletRepo) Save(ctx context.Context, wallet *domain.Wallet) (*domain.Wallet, error) {
	ret := _m.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Wallet) (*domain.Wallet, error)); ok {
		return rf(ctx, wallet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Wallet) *domain.Wallet); ok {
		r0 = rf(ctx, wallet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Wallet) error); ok {
		r1 = rf(ctx, wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWalletRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - wallet *domain.Wallet
func (_e *MockWalletRepo_Expecter) Save(ctx interface{}, wallet interface{}) *MockWalletRepo_Save_Call {
	return &MockWalletRepo_Save_Call{Call: _e.mock.On("Save", ctx, wallet)}
}

func (_c *MockWalletRepo_Save_Call) Run(run func(ctx context.Context, wallet *domain.Wallet)) *MockWalletRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Wallet))
	})
	return _c
}

func (_c *MockWalletRepo_Save_Call) Return(_a0 *domain.Wallet, _a1 error) *MockWalletRepo_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_Save_Call) RunAndReturn(run func(context.Context, *domain.Wallet) (*domain.Wallet, error)) *MockWalletRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepo creates a new instance of MockWalletRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepo {
	mock := &MockWalletRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
